sudo: false
language: ruby
cache: bundler
bundler_args: --retry=3 --jobs=3
rvm:
    - 1.9.3
    - 2.0
    - 2.1
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.2p95
    - ruby-head
    - jruby
    - jruby-head
matrix:
    allow_failures:
    - rvm: 2.2.2p95
    - rvm: jruby
    - rvm: jruby-head
    fast_finish: true