
development:
  adapter: postgresql
  database: mezzo_development
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: postgresql
  database: mezzo_test
  pool: 5
  timeout: 5000
  encoding: utf8

production:
  adapter: postgresql
  database: mezzo_production
  pool: 5
  timeout: 5000
  encoding: utf8
